# Generated by Django 5.2.3 on 2025-07-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_name', models.CharField(max_length=30)),
                ('pst', models.TextField(max_length=400)),
            ],
            options={
                'db_table': 'blogs_tbl',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'user_tbl',
            },
        ),
    ]
